#!/bin/bash
LIBNAME=wiringPi

gcc -l$LIBNAME 2>&1 | grep -q "cannot find -l$LIBNAME"
if [ $? -eq 0 ] ; then
   echo "+----------------------------------------------------------------------------------+"
   echo -e "| \033[1;31mERROR: Library wiringPi not found!\033[0m                           |"
   echo "| Make sure you follow instructions from http://wiringpi.com/download-and-install/ |"
   echo "| to install the wiringPi library on your system first then install this addon.    |"
   echo "+----------------------------------------------------------------------------------+"
   exit 0
else
	echo "Library $LIBNAME found."

	echo "Installing Native Abstractions for Node.js (NAN)..."
	npm install nan

    echo "Rebuiling addon..."
    node-gyp rebuild
fi